apiVersion: "kafka.nais.io/v1"
kind: "Topic"
metadata:
  name: {{topic}}
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: {{kafka}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 336
  acl:
    - team: teamdagpenger
      application: dp-dataprodukter
      access: readwrite
    - team: teamdagpenger
      application: dp-kafka-connect
      access: read
