apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-data-inntekt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  kafka:
    pool: {{kafka.pool}}