apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: dagpengesoknader
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: dagpengesoknader
  description: "Dataprodukt som viser alle dagpengesøknader inkludert utenlandstilsnitt"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT
        I.journalpostId,
        I.opprettetDato,
        I.registrertDato,
        I.skjemaKode,
        I.tittel,
        I.fagsakId,
        U.bostedsland,
        U.arbeidsforhold_eos,
        U.arbeidsforhold_land,
        U.er_utland
      FROM
        (SELECT journalpostId, min(opprettetDato) AS opprettetDato, registrertDato, skjemaKode, tittel, fagsakId 
         FROM `dataprodukt.data_innlop_v2`
         WHERE skjemaKode in ('NAV 04-16.03', 'NAV 04-01.03', 'NAV 04-16.04', 'NAV 04-01.04')
         GROUP BY journalpostId, registrertDato, skjemaKode, tittel, fagsakId) I
      LEFT JOIN
        (SELECT DISTINCT * from `dataprodukt.data_innlop_utland_v2`) U
      ON
        I.journalpostId=U.journalpostId
