apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: bigquerytablesample
spec:
  description: "BigQuery Sample Table"
  datasetRef:
    external: dataprodukt
  friendlyName: journalpost-utland-utenkode6
  view:
    query: "SELECT tittel,type  FROM `teamdagpenger-dev-885f.dataprodukt.data_innlop_v2` LIMIT 100"