name: Deploy BigQuery Views
on: [ workflow_call ]

jobs:
  deploy-view:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ dev-gcp, prod-gcp ]
        include:
          - cluster: dev-gcp
            project: teamdagpenger-dev-885f
          - cluster: prod-gcp
            project: teamdagpenger-prod-9042
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/views/dagpengesoknader.yaml,.nais/views/dagpengesoknader-ident.yaml
          VAR: project=${{ matrix.project }}
          PRINT_PAYLOAD: true