name: Deploy Kafka Topics + Kafka Connectors
on: [ workflow_call ]

jobs:
  deploy-topics:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        topic: [ data-innlop-v2, data-innlop-utland-v2, data-innlop-ident-v1 ]
        cluster: [ dev-gcp, prod-gcp ]
        include:
          - cluster: dev-gcp
            kafka: nav-dev
            project: teamdagpenger-dev-885f
          - cluster: prod-gcp
            kafka: nav-prod
            project: teamdagpenger-prod-9042
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/kafka/topic.yaml,.nais/kafka/connector.yaml
          VAR: topic=${{ matrix.topic }},kafka=${{ matrix.kafka }},project=${{ matrix.project }}
          PRINT_PAYLOAD: true