name: Build and deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2.7.0
        id: build
        with:
          dependency-graph: generate-and-submit
          arguments: --configuration-cache build installDist

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          byosbom: ${{ steps.build.outputs.dependency-graph-file }}
          team: teamdagpenger
          tag: ${{ github.sha }}
          dockerfile: mediator/Dockerfile # optional, default Dockerfile
          docker_context: mediator # optional, default .
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    needs: [ build ]
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/vars/dev.yaml
          PRINT_PAYLOAD: true

  deploy-dev-kafka:
    needs: [ build ]
    #if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-topics.yaml
    secrets: inherit
    with:
      cluster: dev-gcp
      kafka: nav-dev
      project: teamdagpenger-dev-885f

  deploy-dev-views:
    needs: [ build ]
    #if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-views.yaml
    secrets: inherit
    with:
      cluster: dev-gcp
      project: teamdagpenger-dev-885f

  deploy-prod:
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/vars/prod.yaml
          PRINT_PAYLOAD: true

  deploy-prod-kafka:
    if: github.ref == 'refs/heads/main'
    needs: [ build ]
    uses: ./.github/workflows/deploy-topics.yaml
    secrets: inherit
    with:
      cluster: prod-gcp
      kafka: nav-prod
      project: teamdagpenger-prod-9042

  deploy-prod-views:
    if: github.ref == 'refs/heads/main'
    needs: [ build ]
    uses: ./.github/workflows/deploy-views.yaml
    secrets: inherit
    with:
      cluster: prod-gcp
      project: teamdagpenger-prod-9042
